version: '3.9'
services:
  
  redis:
    container_name: rediss
    image: redis:6.2.5
    ports:
      - 6379:6379

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mem


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"